---

- name: Compute Engine instances
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./secret/vars.yaml  
  vars:
      gcp_project: cc-2024
      gcp_cred_kind: serviceaccount
      # gcp_cred_file: definida mediante variable de entorno
      zone: "us-central1-a"
      region: "us-central1"
      machine_type: "e2-micro"
      image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts"
      # required extra-vars: nombre and accion. Use ansible-playbook ... --extra-vars "nombre=server accion=present/absent"

  tasks:

  - name: Gestiona IP address para VM
    google.cloud.gcp_compute_address:
      name: "{{ nombre }}-ip"
      state: "{{accion}}"
      region: "{{ region }}"
      project: "{{ gcp_project }}"
      #service_account_file: definida mediante variable de entorno
      auth_kind: "{{ gcp_cred_kind }}"
    register: gce_ip

  - name: Gestiona instancia de VM
    google.cloud.gcp_compute_instance:
      name: "{{ nombre }}-vm"
      state: "{{accion}}"
      machine_type: "{{ machine_type }}"
      disks:
        - auto_delete: true
          boot: true
          initialize_params:
            source_image: "{{ image }}"
      network_interfaces:
        - access_configs:
            - name: External NAT  # public IP
              nat_ip: "{{ gce_ip }}"
              type: ONE_TO_ONE_NAT
      tags:
        items:
          - http-server
          - https-server
      metadata:
        ssh-keys: "{{usuario}}:{{clave_ssh}}"
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      # service_account_file: definida mediante variable de entorno
      auth_kind: "{{ gcp_cred_kind }}"
    register: gce


  - name: Mensaje recursos eliminados
    ansible.builtin.debug:
      msg:
        - Recursos eliminados {{ nombre }} IP y VM
    when: accion=="absent"

  - name: Mensaje recursos creados (IP y VM)
    ansible.builtin.debug:
      msg:
        - IP {{gce_ip.address}}
        - VM {{gce.name}}
    when: accion=="present"

